### ISSUE TITLE
Question about https://slack.nteract.io

### ISSUE THREAD

**Issue by logankilpatrick** [nteract/nteract.io#303]
Hey all, I wanted to reach out to see how your https://slack.nteract.io page was built. Is this something where you can share the code or set up so the Julia Language can build something like this as well?

**Comment by captainsafia** [comment]
Sure! That homepage is built using a tool called slackin (https://github.com/rauchg/slackin). To use it, you fork the repo and then modify the API keys for your particular slack instance. Then, deploy it wherever (we use vercel.com for all our deployments).

Hope this is helpful!

**Comment by guillefix** [comment]
It seems that the automatic invite isn't working. When I click on slack.nteract.io, I am getting a `This deployment is no longer available.` error

**Comment by logankilpatrick** [comment]
+1 also seeing this

**Comment by captainsafia** [comment]
Well, I have a rather unfortunate update for everyone.

So, the "This deployment is no longer available error" is thrown by our hosting provider, Vercel. They recently issued a major version upgrade of their deployment model. Apps running on the old deployment model, like our Slack inviter, were shutdown if they weren't updated. I had updated our other deployments except this one because I had misinterpreted the info they gave about what deployments were update and which were not.

So, I figured that updating it would be straightforward. Just re-deploy the Slack inviter and re-alias the domains and voila!

But alas, it's not going to be that easy of course. The Slack inviter linked above is no longer updated. It still relies on Slack's legacy model for providing API tokens.

So I searched for a more updated version, when I discovered that unfortunately, Slack no longer provides API access for its `admin.invite` scope, see https://github.com/integrations/slack/issues/1063.

So, we'll probably never be able to re-deploy the Slack inviter again, given that the API permissions needed to support it are no longer available.

With this limitation in mind, perhaps its time that we move our chat community over to Discord...

I'll bring this up during the next weekly meeting and make a plan moving forward.

**Comment by logankilpatrick** [comment]
We just went through this for the Julia Language. We just set the old link as the alias/redirect for the Slack generated invite link. It seems to be doing the job right now.

**Comment by captainsafia** [comment]
>  We just set the old link as the alias/redirect for the Slack generated invite link. It seems to be doing the job right now.

Yeah, I saw a thread about redirecting to the Slack generated invite link. However, the nteract workspace shows the option for the invite link that expires after a set time-period, which increases the maintenance requirements for this.

How are you working around this for Julia? Did you not get the expiry UI or are you automating refreshing the Slack invite URL somehow?

**Comment by logankilpatrick** [comment]
No, sadly we do not. We will just update the link once per month. (I actually forgot this was a thing till now)

**Comment by captainsafia** [comment]
Alright! I've done the needful and update the slack.nteract.io page to redirect to the invite link from Slack. We'll have to keep it  synced but ah well...
