### ISSUE TITLE
kernels/python instructions disregard virtualenv installs

### ISSUE THREAD

**Issue by nils-werner** [nteract/nteract.io#36]
I believe that most users follow one of the two modern methods of managing their Python installations: virtualenvs or Anaconda environments. Hopefully almost nobody runs

    sudo pip install numpy

nowadays anymore.

For those users I find that the instructions on <https://nteract.io/kernels/python> follow an installation model that is not suitable to them.

The instructions ask the user to install an ipython kernel in their home directory using

    python -m ipykernel install --user

This kernel will then become visible to all Hydrogen instances everywhere and overrides all other kernels in all other virtual environments, even if a local kernel is available. This can can create very messy situations with code inside a virtualenv run by an interpreter outside of it. And uninstalling an ipykernel kernel is much much harder than installing one.

The way I understand it, these instructions are only meant for users that do not run Atom from the commandline, and thus outside a virtualenv (which, admittedly, is probably a large number). I see that for them these instructions may be the only way to get Python kernels to work.

However for users that are using virtualenvs and are running Atom from inside one, these instructions can be very destructive. Instead of following the instructions, all they had to do was run

    pip install jupyter

I believe the page should show more of the common possible scenarios and have installation instructions for them.

**Comment by rgbkrk** [comment]
Thanks for the write up. We took some tradeoffs here, and we used the official IPython kernel install documentation from here: http://ipython.readthedocs.io/en/stable/install/kernel_install.html

However, what we wrote omits the virtualenv and conda env instructions that are at the bottom of the IPython kernel install page.

/cc @betatim

**Comment by betatim** [comment]
Until a while back nteract would not find kernels inside a conda environment. I think it was essentially because it was trying to be too smart for its own good. Not sure how hydrogen handles this.

On changing the install instructions: one way forward would be to list how to do it in the case of:

* "--user" install
* conda env
* pip env

it would mean we have to maintain three different sets of instructions. Maybe just adding a sentence below saying "if you use conda envs or virtual envs you probably don't need the `--user`, ask your virtual env expert how to translate this command". This is based on the premise that if you know nothing you probably don't have a virtual env so just copy&pasting the command is the right thing to do. And if you do have a virtualenv you are a bit more experienced and can translate the command to the appropriate one for your case.

**Comment by betatim** [comment]
I'm not sure what environment variables you get on linux/windows when you double click an icon which might make this even more complicated :-/

**Comment by jzf2101** [comment]
Should #42 fix this?
