### ISSUE TITLE
Windows alternative to `source` command

### ISSUE THREAD

**Issue by jruales** [nteract/nteract.io#374]
The page https://nteract.io/kernels (corresponding file on git [here](https://github.com/nteract/nteract.io/blob/main/components/kernels/python.js)) asks the user to run the `source` command to enter the conda env or virtualenv. This only works on Linux or Mac.

On Windows, at least for the pip instructions it would be `my_environment_name\Scripts\activate` instead of `source my_environment_name/bin/activate`

**Comment by captainsafia** [comment]
We don't have the best infrastructure for showing install instructions on different platforms at the moment and have settled on Linux-based instructions since that is what most of the dev team is using at the time.

To make some incremental progress here, we can add a code comment adjacent to that line instructing users of the Windows instructions.
